---
title: "poster_analyses"
author: "MJLee"
date: "4/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries and data info

## libraries
```{r error = FALSE, message = FALSE}
library(tidyverse)
library(vegan)
library(spatialEco)
library(reshape2)
```

## data files
```{r message = FALSE, error = FALSE}
lasioglossum_data1 <- read_csv("Lasioglossum_Sierra.csv")
handnet_data1 <- read_csv("PollinatorSurveys.csv") %>% 
  filter(order == "Hymenoptera" | order == "Diptera" | order == "Coleoptera")
site_metadata <- read_csv("site_info.csv")

order_data <- merge(handnet_data1, site_metadata, by = "lake")

insect_data1 <- merge(handnet_data1, lasioglossum_data1, by = "lake")

lasioglossum_data <- merge(lasioglossum_data1, site_metadata, by = "lake")


# Sierra all bees
all_bees1 <- read_csv("sierra_pollgenera.csv") %>% 
  mutate(
    sex = na_if(sex, "?"),
    lake = na_if(lake, "?"),
    method = na_if(method, "?")
    ) %>% 
  rename("QR_code" = QR)

```

# BY ORDER

## data visualization by order
```{r}
# count by order
# take order_data "and then"
orders <- order_data %>% 
  # group by first the lake sites and then insect order
  group_by(lake, order) %>% 
  # calculate the number of observations per order per lake
  summarise(
    count = length(order)
  )

# remerge with site data
order_lakes_df <- merge(orders, site_metadata, by = "lake")

# multiple side-by-side graphs to visualize order count over elevational gradient
order_fig1 <- ggplot(order_lakes_df, aes(x = elevation, y = count)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Elevation (m)") +
  ylab("Pollinator count") +
  theme_bw()
order_fig1

order_fig2 <- ggplot(order_lakes_df, aes(x = elevation, y = count)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~order) +
  xlab("Elevation (m)") +
  ylab("Pollinator count") +
  theme_bw()
order_fig2

order_fig3 <- ggplot(order_lakes_df, aes(x = elevation, y = count, fill = order, colour = order)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("Elevation (m)") +
  ylab("Pollinator count") +
  theme_bw()
order_fig3
```

## linear models by order
```{r}
lm_order <- lm(count ~ elevation, data = order_lakes_df)
summary(lm_order)

coleoptera <- order_lakes_df %>% 
  filter(order == "Coleoptera")
lm_coleoptera <- lm(count ~ elevation, data = coleoptera)
summary(lm_coleoptera)

diptera <- order_lakes_df %>% 
  filter(order == "Diptera")
lm_diptera <- lm(count ~ elevation, data = diptera)
summary(lm_diptera)

hymenoptera <- order_lakes_df %>% 
  filter(order == "Hymenoptera")
lm_hymenoptera <- lm(count ~ elevation, data = hymenoptera)
summary(lm_hymenoptera)
```


# data visualization of Lasioglossum
```{r}
# count by order
# take order_data "and then"
lasioglossum1 <- lasioglossum_data %>% 
  # group by first the lake sites and then insect order
  group_by(lake, genus) %>% 
  # calculate the number of observations per order per lake
  summarise(
    count = length(genus)
  )

lasioglossum <- merge(lasioglossum1, site_metadata, by = "lake")

# visualize Lasioglossum across the elevational gradient
lasioglossum_fig1 <- ggplot(lasioglossum, aes(x = elevation, y = count)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Elevation (m)") +
  ylab("Lasioglossum count") +
  theme_bw()
lasioglossum_fig1

# visualize all counts across gradient
lasioglossum_fig2 <- ggplot(lasioglossum_data, aes(x = elevation)) +
  geom_bar(stat = "count")
lasioglossum_fig2
```



# genus diversity
```{r message = FALSE, error = FALSE}
# upload genus data
# we did this above in the data info chunk

# first merge all_bees1 with handnet to try and get associated lakes
all_bees2 <- merge(all_bees1, handnet_data1, by = "QR_code", all.x = TRUE) %>% 
  mutate(lake = coalesce(lake.x, lake.y)) %>% 
  select(lake, QR_code, method, family, genus, sex)

# re-merge with site metadata
all_bees <- merge(all_bees2, site_metadata, by = "lake")




###########################
# reformatting data to matrix

#Change from long format to wide. I would pool everything by lake so that the communities represent independent samples
poll_matrix <- dcast(all_bees, elevation ~ genus,value.var="genus",fun.aggregate=length)

# different metrics of diversity
H <- diversity(poll_matrix)
simp <- diversity(poll_matrix, "simpson")

# "paste" columns together
diversity_elev <- as.data.frame(cbind(
  elevation = poll_matrix$elevation,
  H = H <- diversity(poll_matrix),
  Simp = simp <- diversity(poll_matrix, "simpson")
))

# visualize  Shannon's diversity across elevational gradient
hdiversity_fig1 <- ggplot(diversity_elev, aes(x = elevation, y = H)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Elevation (m)") +
  ylab("Shannon's Diversity") +
  theme_bw()
hdiversity_fig1

# linear model by genera Shannon's diversity
lm_genera1 <- lm(H ~ elevation, data = diversity_elev)
summary(lm_genera1)

# visualize  Simpson diversity across elevational gradient
simpdiversity_fig1 <- ggplot(diversity_elev, aes(x = elevation, y = Simp)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Elevation (m)") +
  ylab("Simpson Diversity") +
  theme_bw()
simpdiversity_fig1

# linear model by genera Simpson diversity
lm_genera2 <- lm(Simp ~ elevation, data = diversity_elev)
summary(lm_genera2)


```

